task: nerf
gpus: [0]
exp_name: 'nerf'
scene: 'lego'

train_dataset_module: lib.datasets.nerf.synthetic
test_dataset_module: lib.datasets.nerf.synthetic
network_module: lib.networks.nerf.network
loss_module: lib.train.losses.nerf
evaluator_module: lib.evaluators.nerf
visualizer_module: lib.visualizers.nerf

task_arg:
    N_rays: 1024
    chunk_size: 4096
    white_bkgd: True
    cascade_samples: [64, 128]

network:
    nerf:
        W: 256
        D: 8
        V_D: 1
    xyz_encoder:
        type: 'frequency'
        input_dim: 3
        freq: 10
    dir_encoder:
        type: 'frequency'
        input_dim: 3
        freq: 4

train_dataset:
    data_root: 'data/nerf_synthetic'
    split: 'train'
    input_ratio: 1.
    cams: [0, -1, 1] 

test_dataset:
    data_root: 'data/nerf_synthetic'
    split: 'test'
    input_ratio: 1.
    cams: [0, -1, 100]

train:
    batch_size: 1
    lr: 5e-4
    weight_decay: 0.
    epoch: 400
    scheduler:
        type: 'exponential'
        gamma: 0.1
        decay_epochs: 1000
    num_workers: 4

test:
    batch_size: 1

ep_iter: 500
save_ep: 20
eval_ep: 20       # 10000 iterations
save_latest_ep: 5 # 2500 iterations
log_interval: 10
